- hosts: newnodes
  become: yes
  tasks:
    - name: Add GlusterFS Repository
      apt_repository:
        repo: 'ppa:gluster/glusterfs-3.13'
        codename: xenial
    - name: install GlusterFS on all servers
      apt:
        name: glusterfs-server
        state: present
        update_cache: yes
    - name: Make storage directory on GlusterFS Server
      file:
        path: /opt/shared-storage
        state: directory
        mode: 0755
    - name: Make storage directory to mount on nodes
      file:
        path: /mnt/shared-directory
        state: directory
        mode: 0755
    - name: Add IP address of hosts to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
        state: present
      with_items: "{{ groups.glusters }}"
- hosts: newnodes
  become: yes
  tasks:
    - name: Create mount-point and add it to fstab
      become: true
      become_user: root
      become_method: sudo
      mount:
        name: /mnt/shared-directory
        src: gluster1:/cluster-storage
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
- hosts: newnodes
  become: yes
  tasks:
   - name: Install prerequisites
     apt: name={{item}} update_cache=yes
     with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
   - name: Add Docker GPG key
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg
     run_once: true
   - name:  Add Docker APT repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
     run_once: true
   - name: install Docker
     apt:
       name: docker-ce=18.06.3~ce~3-0~ubuntu
       state: present
       update_cache: true
     run_once: true
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present
   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
     run_once: true
   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'
     run_once: true
   - name: install kubectl=1.13.5-00
     apt:
       name: kubectl
       state: present
       update_cache: true
     run_once: true
   - name: install kubelet=1.13.5-00
     apt:
       name: kubelet
       state: present
       update_cache: true
     run_once: true
   - name: install kubeadm=1.13.5-00
     apt:
       name: kubeadm
       state: present
       update_cache: true
     run_once: true
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: newnodes
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }}"

