- hosts: master
  become: yes
  tasks:
    - name: Bootstarpping Cluster with 10.244.0.0/16 CIDR Address
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.info
      args:
        chdir: $HOME
        creates: cluster_initialized.info
    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> cni_created.info
      args:
        chdir: $HOME
        creates: cni_created.info
