- hosts: master
  become: yes
  tasks:
    - name: Adding Tiller Serviceaccount
      become_user: ubuntu
      shell: kubectl create serviceaccount tiller --namespace kube-system >> tiller_ns_created.info
      args:
        chdir: $HOME
        creates: tiller_ns_created.info
    - name: Copy RBAC File
      become_user: ubuntu
      copy:
        src: helm
        dest: ~/
    - name: Adding Tiller RBAC to Cluster
      become_user: ubuntu
      shell: kubectl create -f ~/helm/tiller_rbac.yaml >> helm_rbac_created.info
      args:
        chdir: $HOME
        creates: helm_rbac_created.info
    - name: Installing HELM
      become_user: ubuntu
      shell: curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash >> helm_installed.info
      args:
        chdir: $HOME
        creates: helm_installed.info
    - name: Initting HELM
      become_user: ubuntu
      shell: helm init --service-account tiller --upgrade >> helm_initted.info
      args:
        chdir: $HOME
        creates: helm_initted.info
    - pause:
        minutes: 1
