- hosts: master
  become: yes
  tasks:
   - name: Creating Registry Namespace
     shell: kubectl create namespace registry >> registry_ns_created.info
     become_user: ubuntu
     args:
       chdir: $HOME
       creates: registry_ns_created.info
   - name: Copy Docker Registry Configuration directory
     become_user: ubuntu
     copy:
       src: registry-with-authentication
       dest: ~/
   - name: Prepairing Docker Registry Ingress Configuration
     become_user: ubuntu
     replace:
       path: ~/registry-with-authentication/registry-ingress.yaml
       regexp: "{{ item.regexp }}"
       replace: "{{ item.var }}"
     with_items:
       - { regexp: 'registry_certificate', var: "{{ registry_certificate }}" } 
       - { regexp: 'registry_address_http', var: "{{ registry_address_http }}" }

   - name: Deploying Docker Registry
     become_user: ubuntu
     shell: kubectl create -f {{ item.yaml }} >> registry_{{ item.file }}.info
     with_items:
       - { yaml: '~/registry-with-authentication/registry-deployment.yaml', file: 'deployment' }
       - { yaml: '~/registry-with-authentication/registry-service.yaml', file: 'service' }
       - { yaml: '~/registry-with-authentication/registry-ingress.yaml', file: 'ingress' }
       - { yaml: '~/registry-with-authentication/configMap-docker.yaml', file: 'configmap' }
       - { yaml: '~/registry-with-authentication/configMap-auth.yaml', file: 'auth' }
     args:
       chdir: $HOME
       creates: registry_{{ item.file }}.info
