apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config-docker
  namespace: registry
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config-docker
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      formatter: text
      fields:
        service: registry
    loglevel: debug
    storage:
      s3:
        accesskey: WMEXRGHAUTYWJEKZ
        secretkey: twVntWeicnwjFiLaLswcwLgrefDoPseaZfVGlNSECaBS
        region: us-east-1
        regionendpoint: http://195.201.220.30:9000
        # Make sure you've created the following bucket.
        bucket: registry
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
      delete:
        enabled: true
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
        readonly:
          enabled: false
    http:
      addr: :5000
