apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: alertmanager_certificate
  namespace: monitoring
spec:
  secretName: alertmanager_certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: alertmanager.url
  dnsNames:
  - alertmanager.url
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - alertmanager.url
