apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: prometheus_certificate
  namespace: monitoring
spec:
  secretName: prometheus_certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: prometheus.url
  dnsNames:
  - prometheus.url
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - prometheus.url
