apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pushgateway_certificate
  namespace: monitoring
spec:
  secretName: pushgateway_certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: pushgateway.url
  dnsNames:
  - pushgateway.url
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - pushgateway.url
