kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-volume
  labels:
    type: local
    namespace_name: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/shared-directory/infrastructure/grafana"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-claim
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      namespace_name: monitoring
